"use strict";
const {createProject200Contact,findDuplicateSourceRows}=require("./project200-contact-identity.js");
const ACCEPTED_FORMATS=Object.freeze(["CSV","JSON"]);
function parseCsv(text) { const lines=String(text).replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean); if(!lines.length)return[]; const headers=lines[0].split(",").map(x=>x.trim()); return lines.slice(1).map((line,i)=>{const values=line.split(",").map(x=>x.trim()); const row={}; headers.forEach((h,j)=>row[h]=values[j]??""); row.__row=i+2; return row;}); }
function parseProject200({format,content,projectId,projectVersion,candidateId,sourceDate,capturedEvidenceReference}) {
  if(!ACCEPTED_FORMATS.includes(format)) return {status:"UNSUPPORTED_FORMAT",acceptedFormats:ACCEPTED_FORMATS,rows:[],errors:[`${format}_NOT_RATIFIED`]};
  let raw; try { raw=format==="CSV"?parseCsv(content):(typeof content==="string"?JSON.parse(content):content); } catch(e){return{status:"PARSE_ERROR",rows:[],errors:["SOURCE_NOT_PARSEABLE"]};}
  if(!Array.isArray(raw)) return {status:"PARSE_ERROR",rows:[],errors:["ROW_ARRAY_REQUIRED"]};
  const candidates=raw.map((row,index)=>({projectId,projectVersion,candidateId,futureAdvisorIdReference:null,sourceRowReference:format==="CSV"?`csv:row${row.__row}`:`json:index${index}`,name:String(row.name||row.nombre||"").trim(),contactMethods:[row.phone||row.telefono?{type:"PHONE",value:String(row.phone||row.telefono),verificationStatus:"UNVERIFIED"}:null,row.email?{type:"EMAIL",value:String(row.email),verificationStatus:"UNVERIFIED"}:null].filter(Boolean),relationship:String(row.relationship||row.relacion||"UNKNOWN"),relationshipContext:String(row.relationshipContext||row.contexto||""),sourceDate,consentStatus:String(row.consentStatus||"NOT_RECORDED"),evidenceReferences:[capturedEvidenceReference]}));
  const duplicates=new Set(findDuplicateSourceRows(candidates));
  const rows=candidates.map((candidate,index)=>{ if(duplicates.has(index)) return {rowStatus:"DUPLICATE_SOURCE_ROW",sourceRowReference:candidate.sourceRowReference,original:candidate}; if(!candidate.name&&!candidate.contactMethods.length)return{rowStatus:"INVALID_ROW",sourceRowReference:candidate.sourceRowReference,errors:["NAME_AND_CONTACT_MISSING"],original:candidate}; if(!candidate.name||!candidate.contactMethods.length)return{rowStatus:"INCOMPLETE_ROW",sourceRowReference:candidate.sourceRowReference,errors:[!candidate.name?"NAME_MISSING":"CONTACT_METHOD_MISSING"],original:candidate}; try{return{rowStatus:"VALID_ROW",sourceRowReference:candidate.sourceRowReference,contact:createProject200Contact(candidate),normalizationLog:["TRIMMED_TEXT","CONTACT_METHODS_EXPLICIT_UNVERIFIED"]};}catch(e){return{rowStatus:"QUARANTINED_ROW",sourceRowReference:candidate.sourceRowReference,errors:[e.message],original:candidate};}});
  return {status:"PARSED_FOR_REVIEW",format,rows,summary:rows.reduce((a,r)=>(a[r.rowStatus]=(a[r.rowStatus]||0)+1,a),{}),createsProspects:false,crossDomainWrite:false};
}
module.exports={ACCEPTED_FORMATS,parseCsv,parseProject200};
