#!/usr/bin/env bash
set -euo pipefail

EXPECTED_SOURCE_HEAD="${CARTERA_110ABCD_EXPECTED_SOURCE_HEAD:-2d9975be06aa2cdf8e494ecd26266612b9de6af3}"
CURRENT_HEAD="$(git rev-parse HEAD)"
ARTIFACT_DIR="artifacts/cartera-110abcd-acceptance"
CLOSURE_PATH="docs/evidence/FORGE_CARTERA_110ABCD_PROGRAM_COMPLETION_PROMOTION_CLOSURE_001.md"

mkdir -p "$ARTIFACT_DIR" "$(dirname "$CLOSURE_PATH")"

echo '========== CARTERA 110A–110D SOURCE GATE =========='
git merge-base --is-ancestor "$EXPECTED_SOURCE_HEAD" "$CURRENT_HEAD"
echo 'SOURCE_ANCESTRY=PASS'

mapfile -t CHANGED_PATHS < <(git diff --name-only "$EXPECTED_SOURCE_HEAD...$CURRENT_HEAD")
if [[ ${#CHANGED_PATHS[@]} -eq 0 ]]; then
  echo 'CARTERA_110_BOUNDED_PATHS=FAIL:NO_DIFF' >&2
  exit 1
fi

for path in "${CHANGED_PATHS[@]}"; do
  case "$path" in
    .github/workflows/cartera-110abcd-combined-acceptance.yml|\
    advisor-os/cartera/cartera-110c-program-promotion-decision-service.js|\
    docs/architecture/source-truth/FORGE_CARTERA_110ABCD_PROGRAM_COMPLETION_AND_PROMOTION_001.md|\
    docs/evidence/FORGE_CARTERA_110ABCD_PROGRAM_COMPLETION_PROMOTION_CLOSURE_001.md|\
    platform/program-governance/cartera-110a-program-completion-manifest.js|\
    platform/program-governance/cartera-110b-promotion-readiness-policy.js|\
    scripts/ci/cartera-110abcd-combined-acceptance.sh|\
    scripts/ci/cartera-110abcd-static-contract.mjs|\
    tests/cartera-110abcd-program-completion-test.mjs)
      ;;
    *)
      echo "CARTERA_110_BOUNDED_PATHS=FAIL:UNAUTHORIZED_PATH:$path" >&2
      exit 1
      ;;
  esac
done

echo 'BOUNDED_PATHS=PASS'
echo 'PRODUCT_UI_MUTATION=NO'
echo 'DATABASE_MUTATION=NOT_AUTHORIZED'
echo 'MAIN_MUTATION=NOT_AUTHORIZED'
echo 'AUTOMATIC_MERGE=FORBIDDEN'

echo '========== CARTERA 110 STATIC CONTRACT =========='
node scripts/ci/cartera-110abcd-static-contract.mjs

echo '========== CARTERA 110A–110D TARGETED TESTS =========='
node --test tests/cartera-110abcd-program-completion-test.mjs
echo 'CARTERA_110_TARGETED_TESTS=PASS'

cat > "$CLOSURE_PATH" <<EOF
# FORGE CARTERA 110A–110D — PROGRAM COMPLETION AND PROMOTION CLOSURE 001

\`\`\`text
STATUS=ACCEPTED
SOURCE_HEAD=$EXPECTED_SOURCE_HEAD
ACCEPTANCE_HEAD=$CURRENT_HEAD
WORKFLOW_RUN=${GITHUB_RUN_ID:-LOCAL}
WORKFLOW_JOB=${GITHUB_JOB:-LOCAL}
SOURCE_ANCESTRY=PASS
BOUNDED_PATHS=PASS
CARTERA_110_STATIC_CONTRACT=PASS
CARTERA_110_TARGETED_TESTS=PASS
CARTERA_110A_PROGRAM_COMPLETION_MANIFEST=PASS
CARTERA_110B_PROMOTION_READINESS_POLICY=PASS
CARTERA_110C_GOVERNED_DECISION=PASS
CARTERA_110D_ACCEPTANCE_AND_HANDOFF=PASS
CARTERA_100_COMPLETE=YES
CARTERA_RELATIONSHIP_INTELLIGENCE_ROADMAP_COMPLETE=YES
CARTERA_PROGRAM_COMPLETION=VERIFIED
PROMOTION_READINESS=REVIEW_REQUIRED
PROMOTION_DECISION=HOLD
BASE_CHAIN_MERGED=NO
CURRENT_MAIN_HEAD_VERIFIED=NO
BOARD_APPROVAL=NOT_GRANTED
MERGE_AUTHORIZATION=NOT_GRANTED
AUTOMATIC_MERGE=FORBIDDEN
MAIN_MUTATION=NOT_AUTHORIZED
DATABASE_MUTATION=NOT_AUTHORIZED
PRODUCT_UI_MUTATION=NO
ACCOUNT_MUTATION=NOT_AUTHORIZED
CARTERA_110A_COMPLETE=YES
CARTERA_110B_COMPLETE=YES
CARTERA_110C_COMPLETE=YES
CARTERA_110D_COMPLETE=YES
CARTERA_110_COMPLETE=YES
NEXT=CARTERA_CONTROLLED_PROMOTION_AUTHORIZATION
\`\`\`
EOF

cp "$CLOSURE_PATH" "$ARTIFACT_DIR/closure.md"
printf '%s\n' "${CHANGED_PATHS[@]}" > "$ARTIFACT_DIR/changed-paths.txt"
cat > "$ARTIFACT_DIR/summary.txt" <<EOF
CARTERA_110ABCD_ACCEPTANCE=PASS
SOURCE_HEAD=$EXPECTED_SOURCE_HEAD
ACCEPTANCE_HEAD=$CURRENT_HEAD
CARTERA_PROGRAM_COMPLETION=VERIFIED
PROMOTION_READINESS=REVIEW_REQUIRED
PROMOTION_DECISION=HOLD
MERGE_AUTHORIZATION=NOT_GRANTED
MAIN_MUTATION=NOT_AUTHORIZED
DATABASE_MUTATION=NOT_AUTHORIZED
PRODUCT_UI_MUTATION=NO
EOF

echo 'CARTERA_110ABCD_ACCEPTANCE=PASS'
echo 'CARTERA_PROGRAM_COMPLETION=VERIFIED'
echo 'PROMOTION_READINESS=REVIEW_REQUIRED'
echo 'PROMOTION_DECISION=HOLD'
echo 'MERGE_AUTHORIZATION=NOT_GRANTED'
echo 'CARTERA_110A_COMPLETE=YES'
echo 'CARTERA_110B_COMPLETE=YES'
echo 'CARTERA_110C_COMPLETE=YES'
echo 'CARTERA_110D_COMPLETE=YES'
echo 'CARTERA_110_COMPLETE=YES'
