#!/usr/bin/env bash
set -euo pipefail

CURRENT_MAIN_SOURCE_HEAD="${CARTERA_120_CURRENT_MAIN_HEAD:-9d014116f6b3f0a626d8848d680a5c607f924d99}"
ACCEPTED_PROGRAM_HEAD="${CARTERA_120_ACCEPTED_PROGRAM_HEAD:-b83a37abe3eb8b3a48c2fe89940b562e1367bfcc}"
EXPECTED_MERGE_BASE="${CARTERA_120_MERGE_BASE:-a060fde0b5b2f38e0912f54f47dc4f141c21e45c}"
CURRENT_HEAD="$(git rev-parse HEAD)"
ARTIFACT_DIR="artifacts/cartera-120abcd-acceptance"
CLOSURE_PATH="docs/evidence/FORGE_CARTERA_120ABCD_CONTROLLED_PROMOTION_AUTHORIZATION_CLOSURE_001.md"
SOURCE_CLOSURE_PATH="docs/evidence/FORGE_CARTERA_110ABCD_PROGRAM_COMPLETION_PROMOTION_CLOSURE_001.md"

mkdir -p "$ARTIFACT_DIR" "$(dirname "$CLOSURE_PATH")"
exec > >(tee "$ARTIFACT_DIR/acceptance.log") 2>&1

echo '========== CARTERA 120A CURRENT-MAIN RECONCILIATION =========='
git merge-base --is-ancestor "$CURRENT_MAIN_SOURCE_HEAD" "$CURRENT_HEAD"
echo 'CURRENT_MAIN_ANCESTRY=PASS'

git cat-file -e "$ACCEPTED_PROGRAM_HEAD^{commit}"
ACTUAL_MERGE_BASE="$(git merge-base "$CURRENT_MAIN_SOURCE_HEAD" "$ACCEPTED_PROGRAM_HEAD")"
[[ "$ACTUAL_MERGE_BASE" == "$EXPECTED_MERGE_BASE" ]]
echo "MERGE_BASE=$ACTUAL_MERGE_BASE"

read -r MAIN_AHEAD PROGRAM_AHEAD < <(git rev-list --left-right --count "$CURRENT_MAIN_SOURCE_HEAD...$ACCEPTED_PROGRAM_HEAD")
[[ "$MAIN_AHEAD" == '388' ]]
[[ "$PROGRAM_AHEAD" == '594' ]]
echo "CURRENT_MAIN_AHEAD_BY=$MAIN_AHEAD"
echo "ACCEPTED_PROGRAM_AHEAD_BY=$PROGRAM_AHEAD"
echo 'HISTORY_STATE=DIVERGED'
echo 'PROMOTION_STRATEGY=SELECTIVE_CURRENT_MAIN_PROMOTION'
echo 'FULL_HISTORY_MERGE=FORBIDDEN'

git show "$ACCEPTED_PROGRAM_HEAD:$SOURCE_CLOSURE_PATH" > "$ARTIFACT_DIR/source-110-closure.md"
grep -q '^CARTERA_110_COMPLETE=YES$' "$ARTIFACT_DIR/source-110-closure.md"
grep -q '^CARTERA_PROGRAM_COMPLETION=VERIFIED$' "$ARTIFACT_DIR/source-110-closure.md"
grep -q '^PROMOTION_DECISION=HOLD$' "$ARTIFACT_DIR/source-110-closure.md"
grep -q '^NEXT=CARTERA_CONTROLLED_PROMOTION_AUTHORIZATION$' "$ARTIFACT_DIR/source-110-closure.md"
echo 'SOURCE_110_CLOSURE=VERIFIED'

echo '========== CARTERA 120 BOUNDED PATHS =========='
mapfile -t CHANGED_PATHS < <(git diff --name-only "$CURRENT_MAIN_SOURCE_HEAD...$CURRENT_HEAD")
if [[ ${#CHANGED_PATHS[@]} -eq 0 ]]; then
  echo 'CARTERA_120_BOUNDED_PATHS=FAIL:NO_DIFF' >&2
  exit 1
fi
for path in "${CHANGED_PATHS[@]}"; do
  case "$path" in
    .github/workflows/cartera-120abcd-combined-acceptance.yml|\
    advisor-os/cartera/cartera-120c-controlled-promotion-authorization.js|\
    docs/architecture/source-truth/FORGE_CARTERA_120ABCD_CONTROLLED_PROMOTION_AUTHORIZATION_001.md|\
    docs/evidence/FORGE_CARTERA_120ABCD_CONTROLLED_PROMOTION_AUTHORIZATION_CLOSURE_001.md|\
    platform/program-governance/cartera-120a-current-main-reconciliation.js|\
    platform/program-governance/cartera-120b-selective-promotion-manifest.js|\
    scripts/ci/cartera-120abcd-combined-acceptance.sh|\
    scripts/ci/cartera-120abcd-static-contract.mjs|\
    tests/cartera-120abcd-controlled-promotion-authorization-test.mjs)
      ;;
    *)
      echo "CARTERA_120_BOUNDED_PATHS=FAIL:UNAUTHORIZED_PATH:$path" >&2
      exit 1
      ;;
  esac
done
printf '%s\n' "${CHANGED_PATHS[@]}" > "$ARTIFACT_DIR/changed-paths.txt"
echo 'BOUNDED_PATHS=PASS'

echo 'PRODUCT_UI_MUTATION=NO'
echo 'DATABASE_MUTATION=NO'
echo 'ACCOUNT_MUTATION=NO'
echo 'MAIN_MUTATION=NO'
echo 'DEPLOYMENT=NO'
echo 'AUTOMATIC_MERGE=FORBIDDEN'

echo '========== CARTERA 120 STATIC CONTRACT =========='
node scripts/ci/cartera-120abcd-static-contract.mjs

echo '========== CARTERA 120A–120D TARGETED TESTS =========='
node --test tests/cartera-120abcd-controlled-promotion-authorization-test.mjs
echo 'CARTERA_120_TARGETED_TESTS=PASS'

cat > "$CLOSURE_PATH" <<EOF
# FORGE CARTERA 120A–120D — CONTROLLED PROMOTION AUTHORIZATION CLOSURE 001

\`\`\`text
STATUS=ACCEPTED
CURRENT_MAIN_SOURCE_HEAD=$CURRENT_MAIN_SOURCE_HEAD
ACCEPTED_PROGRAM_HEAD=$ACCEPTED_PROGRAM_HEAD
MERGE_BASE=$ACTUAL_MERGE_BASE
ACCEPTANCE_HEAD=$CURRENT_HEAD
WORKFLOW_RUN=${GITHUB_RUN_ID:-LOCAL}
WORKFLOW_JOB=${GITHUB_JOB:-LOCAL}
CURRENT_MAIN_ANCESTRY=PASS
SOURCE_110_CLOSURE=VERIFIED
CURRENT_MAIN_AHEAD_BY=$MAIN_AHEAD
ACCEPTED_PROGRAM_AHEAD_BY=$PROGRAM_AHEAD
HISTORY_STATE=DIVERGED
BOUNDED_PATHS=PASS
CARTERA_120_STATIC_CONTRACT=PASS
CARTERA_120_TARGETED_TESTS=PASS
CARTERA_120A_CURRENT_MAIN_RECONCILIATION=PASS
CARTERA_120B_SELECTIVE_MANIFEST_CONTRACT=PASS
CARTERA_120C_AUTHORIZATION_BOUNDARY=PASS
CARTERA_120D_ACCEPTANCE_AND_CLOSURE=PASS
PROMOTION_STRATEGY=SELECTIVE_CURRENT_MAIN_PROMOTION
FULL_HISTORY_MERGE=FORBIDDEN
STACKED_BRANCH_MERGE=FORBIDDEN
PROMOTION_AUTHORIZATION=NOT_GRANTED
PROMOTION_DECISION=HOLD
BOARD_APPROVAL=NOT_GRANTED
MERGE_AUTHORIZATION=NOT_GRANTED
EXACT_AUTHORIZATION_PHRASE_RECEIVED=NO
FILES_COPIED=0
FILES_RECONCILED=0
PRODUCT_UI_MUTATION=NO
DATABASE_MUTATION=NO
ACCOUNT_MUTATION=NO
MAIN_MUTATION=NO
DEPLOYMENT=NO
CARTERA_120A_COMPLETE=YES
CARTERA_120B_COMPLETE=YES
CARTERA_120C_COMPLETE=YES
CARTERA_120D_COMPLETE=YES
CARTERA_120_COMPLETE=YES
NEXT=CARTERA_130_HEAD_BOUND_SELECTIVE_PROMOTION
\`\`\`
EOF

cp "$CLOSURE_PATH" "$ARTIFACT_DIR/closure.md"
cat > "$ARTIFACT_DIR/result.env" <<EOF
CARTERA_120_ACCEPTANCE_HEAD=$CURRENT_HEAD
CARTERA_120_CURRENT_MAIN_SOURCE_HEAD=$CURRENT_MAIN_SOURCE_HEAD
CARTERA_120_ACCEPTED_PROGRAM_HEAD=$ACCEPTED_PROGRAM_HEAD
CARTERA_120_MERGE_BASE=$ACTUAL_MERGE_BASE
CARTERA_120A_CURRENT_MAIN_RECONCILIATION=PASS
CARTERA_120B_SELECTIVE_MANIFEST_CONTRACT=PASS
CARTERA_120C_AUTHORIZATION_BOUNDARY=PASS
CARTERA_120D_ACCEPTANCE_AND_CLOSURE=PASS
PROMOTION_STRATEGY=SELECTIVE_CURRENT_MAIN_PROMOTION
PROMOTION_DECISION=HOLD
PROMOTION_AUTHORIZATION=NOT_GRANTED
FILES_COPIED=0
FILES_RECONCILED=0
PRODUCT_UI_MUTATION=NO
DATABASE_MUTATION=NO
MAIN_MUTATION=NO
DEPLOYMENT=NO
CARTERA_120_COMPLETE=YES
EOF
cat "$ARTIFACT_DIR/result.env"
