/**
 * Forge Discovery Signal Taxonomy
 */
const SIGNAL_TYPES = {
  PRODUCT_INTEREST: 'PRODUCT_INTEREST',
  PRODUCT_COMPARISON: 'PRODUCT_COMPARISON',
  NETWORK_SIGNAL: 'NETWORK_SIGNAL',
  RELATIONSHIP_SIGNAL: 'RELATIONSHIP_SIGNAL',
  SENTIMENT_SIGNAL: 'SENTIMENT_SIGNAL',
  TIMING_SIGNAL: 'TIMING_SIGNAL',
  OBJECTION_SIGNAL: 'OBJECTION_SIGNAL',
  UNCERTAINTY_SIGNAL: 'UNCERTAINTY_SIGNAL',
  LIFE_EVENT_SIGNAL: 'LIFE_EVENT_SIGNAL'
};

module.exports = {
  SIGNAL_TYPES
};
