export const TRUTH_TYPES = Object.freeze({
  RAW_EVIDENCE: 'RAW_EVIDENCE',
  EVIDENCE_PACKET: 'EVIDENCE_PACKET',
  FACT: 'FACT',
  SOURCE_TRUTH: 'SOURCE_TRUTH',
  RULE: 'RULE',
  RULE_SNAPSHOT: 'RULE_SNAPSHOT',
  PRODUCT_TRUTH: 'PRODUCT_TRUTH',
  POLICY_TRUTH: 'POLICY_TRUTH',
  FORECAST: 'FORECAST',
  ASSUMPTION: 'ASSUMPTION',
  UNKNOWN: 'UNKNOWN',
  RECOMMENDATION: 'RECOMMENDATION',
  DECISION_SUPPORT: 'DECISION_SUPPORT',
  AI_INTERPRETATION: 'AI_INTERPRETATION',
  AI_EXTRACTION_CANDIDATE: 'AI_EXTRACTION_CANDIDATE',
  AI_CLASSIFICATION_CANDIDATE: 'AI_CLASSIFICATION_CANDIDATE',
  USER_INPUT: 'USER_INPUT',
  MANUAL_OVERRIDE: 'MANUAL_OVERRIDE',
  HUMAN_DECISION: 'HUMAN_DECISION',
});

export const KNOWN_TRUTH_TYPES = Object.freeze(Object.values(TRUTH_TYPES));

export function isKnownTruthType(truthType) {
  return KNOWN_TRUTH_TYPES.includes(truthType);
}
